// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function InitWhatsApp(arg1:string):Promise<void>;

export function SendMsg(arg1:string):Promise<boolean>;

export function SendNumber(arg1:string):Promise<boolean>;
