// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitWhatsApp(arg1) {
  return window['go']['main']['App']['InitWhatsApp'](arg1);
}

export function SendMsg(arg1) {
  return window['go']['main']['App']['SendMsg'](arg1);
}

export function SendNumber(arg1) {
  return window['go']['main']['App']['SendNumber'](arg1);
}
